name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    name: Build (${{ matrix.os }}, OTP-${{ matrix.otp_version }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        otp_version: [23]
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Extract branch name
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Cache Hex packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/rebar3/hex/hexpm/packages
        key: ${{ runner.os }}-${{ steps.extract_branch.outputs.branch }}-otp-${{ matrix.otp_version }}-hex-${{ hashFiles(format('{0}{1}', github.workspace, '/rebar.lock')) }}
        restore-keys: |
          ${{ runner.os }}-${{ steps.extract_branch.outputs.branch }}-otp-${{ matrix.otp_version }}-hex-
    - name: Compile
      run: rebar3 compile
    - name: CT tests
      run: rebar3 ct
    - name: Dialyzer
      run: rebar3 dialyzer
    - name: Code coverage
      run: rebar3 cover
    - name: Generate coverage report
      run: rebar3 covertool generate
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash) -f _build/test/covertool/imap_utf7.covertool.xml
